/*
 * TaskJPanel.java
 *
 * Created on 18 de julio de 2008, 12:14
 */
package com.cartiec.jrenamer;

import java.util.HashMap;
import javax.swing.AbstractListModel;

/**
 *
 * @author  Tonny
 */
public class TaskJPanel extends javax.swing.JPanel {

    LstModel lstModel = new LstModel();

    /** Creates new form TaskJPanel */
    public TaskJPanel() {
        initComponents();
    }

    public void setData(HashMap<String, Integer> map) {
        lstModel.setMap(map);
    }

    class LstModel extends AbstractListModel {
        HashMap<String, Integer> map = null;

        public int getSize() {
            return map.size();
        }

        public Object getElementAt(int i) {
            return map.keySet().toArray()[i];
        }

        public HashMap<String, Integer> getMap() {
            return map;
        }

        public void setMap(HashMap<String, Integer> map) {
            this.map = map;
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lst = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        lst.setModel(lstModel);
        jScrollPane1.setViewportView(lst);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setPreferredSize(new java.awt.Dimension(34, 152));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cartiec/jrenamer/res/icons32x32/go-top.png"))); // NOI18N
        jButton1.setPreferredSize(new java.awt.Dimension(34, 34));
        jPanel1.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cartiec/jrenamer/res/icons32x32/go-up.png"))); // NOI18N
        jButton2.setPreferredSize(new java.awt.Dimension(34, 34));
        jPanel1.add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cartiec/jrenamer/res/icons32x32/go-down.png"))); // NOI18N
        jButton3.setPreferredSize(new java.awt.Dimension(34, 34));
        jPanel1.add(jButton3);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cartiec/jrenamer/res/icons32x32/go-bottom.png"))); // NOI18N
        jButton4.setPreferredSize(new java.awt.Dimension(34, 34));
        jPanel1.add(jButton4);

        add(jPanel1, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lst;
    // End of variables declaration//GEN-END:variables
}
